version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@wordpress/env"
    versions:
    - 3.0.1
    - 3.0.2
    - 4.0.1
    - 4.0.2
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: ini
    versions:
    - 1.3.7
